### ISSUE TITLE
ZSTD_compressStream2 binding does not confirm that the structures are initialized

### ISSUE THREAD

**Issue by 20kdc** [TechnologicalPizza/SharpZstd#2]
I don't know *how* to get this to be checked, or even if it can be checked, so close this issue if there's no way to do this, but I recently found a bug in space-wizards/RobustToolbox where `ZSTD_compressStream2` was being given an uninitialized `ZSTD_inBuffer` structure which caused crashes on release (but not debug).

It's definitely an issue on RT's side, I just figured it'd be useful to know if there was a way to get this to be compile-time-assured of not happening again since it was definitely one of those hair-removing bugs.

**Comment by TechPizzaDev** [comment]
That is one of the curses of using unsafe. The requirement of initializing fields is not there and Zstd did not like the garbage. 
I haven't heard of an analyzer that specifically checks for initializing fields so this is mostly out of the control of the library.  
I could generate overloads that take `ref` instead of a pointer, but that is quite a lot of work and introduces slight overhead.

**Comment by 20kdc** [comment]
Fair enough - thank you anyway. I simply wanted to confirm if there was some easy way on your side to help with this, but that definitely appears not to be the case.
